
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5439/postgres"
    username: postgres
    password: postgres
  liquibase:
    change-log: "classpath:db/changelog/migrations.xml"

api_key: "imNotApiKey"

event:
  crone:
    time: "*/30 * * * * *"
    zone: "Europe/Warsaw"
  response:
    post:
      url: "http://localhost:8080/api/eipa/event/consumer"

