version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eipa
    ports:
      - '5439:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local